// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#include "NativeBrNetworkListener.hpp"  // my header
#include "NativeBrBaseViewModel.hpp"

namespace djinni_generated {

NativeBrNetworkListener::NativeBrNetworkListener() : ::djinni::JniInterface<::biblereader::BrNetworkListener, NativeBrNetworkListener>() {}

NativeBrNetworkListener::~NativeBrNetworkListener() = default;

NativeBrNetworkListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeBrNetworkListener::JavaProxy::~JavaProxy() = default;

void NativeBrNetworkListener::JavaProxy::complete(const std::shared_ptr<::biblereader::BrBaseViewModel> & c_view_model) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeBrNetworkListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_complete,
                           ::djinni::get(::djinni_generated::NativeBrBaseViewModel::fromCpp(jniEnv, c_view_model)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
