// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#include "NativeBrBaseRecord.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeBrBaseRecord::NativeBrBaseRecord() = default;

NativeBrBaseRecord::~NativeBrBaseRecord() = default;

auto NativeBrBaseRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeBrBaseRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.xml)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeBrBaseRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeBrBaseRecord>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mXml))};
}

}  // namespace djinni_generated
