// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#include "NativeBrNetworkListener.hpp"  // my header

namespace djinni_generated {

NativeBrNetworkListener::NativeBrNetworkListener() : ::djinni::JniInterface<::biblereader::BrNetworkListener, NativeBrNetworkListener>() {}

NativeBrNetworkListener::~NativeBrNetworkListener() = default;

NativeBrNetworkListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeBrNetworkListener::JavaProxy::~JavaProxy() = default;

void NativeBrNetworkListener::JavaProxy::complete() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeBrNetworkListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_complete);
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
