// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#pragma once

#include "base_view_model.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBaseViewModel final : ::djinni::JniInterface<::biblereader::BaseViewModel, NativeBaseViewModel> {
public:
    using CppType = std::shared_ptr<::biblereader::BaseViewModel>;
    using CppOptType = std::shared_ptr<::biblereader::BaseViewModel>;
    using JniType = jobject;

    using Boxed = NativeBaseViewModel;

    ~NativeBaseViewModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeBaseViewModel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeBaseViewModel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeBaseViewModel();
    friend ::djinni::JniClass<NativeBaseViewModel>;
    friend ::djinni::JniInterface<::biblereader::BaseViewModel, NativeBaseViewModel>;

};

}  // namespace djinni_generated
