// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

#pragma once

#include "djinni_support.hpp"
#include "network_manager.hpp"

namespace djinni_generated {

class NativeNetworkManager final : ::djinni::JniInterface<::biblereader::NetworkManager, NativeNetworkManager> {
public:
    using CppType = std::shared_ptr<::biblereader::NetworkManager>;
    using CppOptType = std::shared_ptr<::biblereader::NetworkManager>;
    using JniType = jobject;

    using Boxed = NativeNetworkManager;

    ~NativeNetworkManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeNetworkManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeNetworkManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeNetworkManager();
    friend ::djinni::JniClass<NativeNetworkManager>;
    friend ::djinni::JniInterface<::biblereader::NetworkManager, NativeNetworkManager>;

};

}  // namespace djinni_generated
