// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#include "NativeBrNetworkManager.hpp"  // my header
#include "NativeBrNetworkListener.hpp"
#include "NativeBrNetworkManager.hpp"

namespace djinni_generated {

NativeBrNetworkManager::NativeBrNetworkManager() : ::djinni::JniInterface<::biblereader::BrNetworkManager, NativeBrNetworkManager>("com/thoughtsofanintrovert/brDjinni/BrNetworkManager$CppProxy") {}

NativeBrNetworkManager::~NativeBrNetworkManager() = default;


CJNIEXPORT void JNICALL Java_com_thoughtsofanintrovert_brDjinni_BrNetworkManager_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::biblereader::BrNetworkManager>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_thoughtsofanintrovert_brDjinni_BrNetworkManager_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::biblereader::BrNetworkManager::create();
        return ::djinni::release(::djinni_generated::NativeBrNetworkManager::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_thoughtsofanintrovert_brDjinni_BrNetworkManager_00024CppProxy_native_1getBibleBooks(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_listener)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::biblereader::BrNetworkManager>(nativeRef);
        ref->get_bible_books(::djinni_generated::NativeBrNetworkListener::toCpp(jniEnv, j_listener));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
