// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#pragma once

#include "br_base_view_model.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBrBaseViewModel final : ::djinni::JniInterface<::biblereader::BrBaseViewModel, NativeBrBaseViewModel> {
public:
    using CppType = std::shared_ptr<::biblereader::BrBaseViewModel>;
    using CppOptType = std::shared_ptr<::biblereader::BrBaseViewModel>;
    using JniType = jobject;

    using Boxed = NativeBrBaseViewModel;

    ~NativeBrBaseViewModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeBrBaseViewModel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeBrBaseViewModel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeBrBaseViewModel();
    friend ::djinni::JniClass<NativeBrBaseViewModel>;
    friend ::djinni::JniInterface<::biblereader::BrBaseViewModel, NativeBrBaseViewModel>;

};

}  // namespace djinni_generated
