// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#pragma once

#include "base_record.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBaseRecord final {
public:
    using CppType = ::biblereader::BaseRecord;
    using JniType = jobject;

    using Boxed = NativeBaseRecord;

    ~NativeBaseRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeBaseRecord();
    friend ::djinni::JniClass<NativeBaseRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/thoughtsofanintrovert/brDjinni/BaseRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mXml { ::djinni::jniGetFieldID(clazz.get(), "mXml", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
