// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#pragma once

#include "br_network_manager.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBrNetworkManager final : ::djinni::JniInterface<::biblereader::BrNetworkManager, NativeBrNetworkManager> {
public:
    using CppType = std::shared_ptr<::biblereader::BrNetworkManager>;
    using CppOptType = std::shared_ptr<::biblereader::BrNetworkManager>;
    using JniType = jobject;

    using Boxed = NativeBrNetworkManager;

    ~NativeBrNetworkManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeBrNetworkManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeBrNetworkManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeBrNetworkManager();
    friend ::djinni::JniClass<NativeBrNetworkManager>;
    friend ::djinni::JniInterface<::biblereader::BrNetworkManager, NativeBrNetworkManager>;

};

}  // namespace djinni_generated
