// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

package com.thoughtsofanintrovert.brDjinni;

public final class BaseRecord {


    /*package*/ final String mXml;

    public BaseRecord(
            String xml) {
        this.mXml = xml;
    }

    public String getXml() {
        return mXml;
    }

    @Override
    public String toString() {
        return "BaseRecord{" +
                "mXml=" + mXml +
        "}";
    }

}
