// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

package com.thoughtsofanintrovert.brDjinni;

public final class BrBaseRecord {


    /*package*/ final String mXml;

    public BrBaseRecord(
            String xml) {
        this.mXml = xml;
    }

    public String getXml() {
        return mXml;
    }

    @Override
    public String toString() {
        return "BrBaseRecord{" +
                "mXml=" + mXml +
        "}";
    }

}
