// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

package com.thoughtsofanintrovert.brDjinni;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class BrNetworkManager {
    public abstract ArrayList<String> getBibleBooks(BrNetworkListener listener);

    public static native BrNetworkManager create();

    private static final class CppProxy extends BrNetworkManager
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public ArrayList<String> getBibleBooks(BrNetworkListener listener)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getBibleBooks(this.nativeRef, listener);
        }
        private native ArrayList<String> native_getBibleBooks(long _nativeRef, BrNetworkListener listener);
    }
}
