// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

package com.thoughtsofanintrovert.brDjinni;

public abstract class BrNetworkListener {
    public abstract void complete();
}
