// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

package com.thoughtsofanintrovert.brDjinni;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class NetworkManager {
    public abstract void getBibleBooks(NetworkListener listener);

    public static native NetworkManager create();

    private static final class CppProxy extends NetworkManager
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void getBibleBooks(NetworkListener listener)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_getBibleBooks(this.nativeRef, listener);
        }
        private native void native_getBibleBooks(long _nativeRef, NetworkListener listener);
    }
}
