// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

package com.thoughtsofanintrovert.brDjinni;

public abstract class NetworkListener {
    public abstract void complete(BaseViewModel viewModel);
}
