// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#import "BRBaseRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto BaseRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.xml)};
}

auto BaseRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[BRBaseRecord alloc] initWithXml:(::djinni::String::fromCpp(cpp.xml))];
}

}  // namespace djinni_generated
