// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#include "base_view_model.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class BRBaseViewModel;

namespace djinni_generated {

class BaseViewModel
{
public:
    using CppType = std::shared_ptr<::biblereader::BaseViewModel>;
    using CppOptType = std::shared_ptr<::biblereader::BaseViewModel>;
    using ObjcType = BRBaseViewModel*;

    using Boxed = BaseViewModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

