// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#import "BrBaseRecord.h"
#include "br_base_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class BrBaseRecord;

namespace djinni_generated {

struct BrBaseRecord
{
    using CppType = ::biblereader::BrBaseRecord;
    using ObjcType = BrBaseRecord*;

    using Boxed = BrBaseRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
