// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#import "BRBaseRecord.h"
#include "base_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class BRBaseRecord;

namespace djinni_generated {

struct BaseRecord
{
    using CppType = ::biblereader::BaseRecord;
    using ObjcType = BRBaseRecord*;

    using Boxed = BaseRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
