// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#import <Foundation/Foundation.h>
@class BrBaseViewModel;


@interface BrBaseViewModel : NSObject

+ (nullable BrBaseViewModel *)create;

- (void)setXml:(nonnull NSString *)xml;

@end
