// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#import "BrBaseRecord.h"


@implementation BrBaseRecord

- (nonnull instancetype)initWithXml:(nonnull NSString *)xml
{
    if (self = [super init]) {
        _xml = [xml copy];
    }
    return self;
}

+ (nonnull instancetype)brBaseRecordWithXml:(nonnull NSString *)xml
{
    return [[self alloc] initWithXml:xml];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p xml:%@>", self.class, (void *)self, self.xml];
}

@end
