// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#import "BRBaseViewModel+Private.h"
#import "BRBaseViewModel.h"
#import "BRBaseViewModel+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface BRBaseViewModel ()

- (id)initWithCpp:(const std::shared_ptr<::biblereader::BaseViewModel>&)cppRef;

@end

@implementation BRBaseViewModel {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::biblereader::BaseViewModel>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::biblereader::BaseViewModel>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable BRBaseViewModel *)create {
    try {
        auto r = ::biblereader::BaseViewModel::create();
        return ::djinni_generated::BaseViewModel::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setXml:(nonnull NSString *)xml {
    try {
        _cppRefHandle.get()->set_xml(::djinni::String::toCpp(xml));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getXml {
    try {
        auto r = _cppRefHandle.get()->get_xml();
        return ::djinni::String::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto BaseViewModel::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto BaseViewModel::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<BRBaseViewModel>(cpp);
}

}  // namespace djinni_generated

@end
