// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#import "BrBaseViewModel+Private.h"
#import "BrBaseViewModel.h"
#import "BrBaseViewModel+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface BrBaseViewModel ()

- (id)initWithCpp:(const std::shared_ptr<::biblereader::BrBaseViewModel>&)cppRef;

@end

@implementation BrBaseViewModel {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::biblereader::BrBaseViewModel>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::biblereader::BrBaseViewModel>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable BrBaseViewModel *)create {
    try {
        auto r = ::biblereader::BrBaseViewModel::create();
        return ::djinni_generated::BrBaseViewModel::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setXml:(nonnull NSString *)xml {
    try {
        _cppRefHandle.get()->set_xml(::djinni::String::toCpp(xml));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto BrBaseViewModel::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto BrBaseViewModel::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<BrBaseViewModel>(cpp);
}

}  // namespace djinni_generated

@end
