// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#import <Foundation/Foundation.h>

@interface BrBaseRecord : NSObject
- (nonnull instancetype)initWithXml:(nonnull NSString *)xml;
+ (nonnull instancetype)brBaseRecordWithXml:(nonnull NSString *)xml;

@property (nonatomic, readonly, nonnull) NSString * xml;

@end
