// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#import <Foundation/Foundation.h>

@interface BRBaseRecord : NSObject
- (nonnull instancetype)initWithXml:(nonnull NSString *)xml;
+ (nonnull instancetype)baseRecordWithXml:(nonnull NSString *)xml;

@property (nonatomic, readonly, nonnull) NSString * xml;

@end
