// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#import "BrBaseRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto BrBaseRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.xml)};
}

auto BrBaseRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[BrBaseRecord alloc] initWithXml:(::djinni::String::fromCpp(cpp.xml))];
}

}  // namespace djinni_generated
