// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#import <Foundation/Foundation.h>
@class BRBaseViewModel;


@interface BRBaseViewModel : NSObject

+ (nullable BRBaseViewModel *)create;

- (void)setXml:(nonnull NSString *)xml;

@end
