// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#include "br_base_view_model.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class BrBaseViewModel;

namespace djinni_generated {

class BrBaseViewModel
{
public:
    using CppType = std::shared_ptr<::biblereader::BrBaseViewModel>;
    using CppOptType = std::shared_ptr<::biblereader::BrBaseViewModel>;
    using ObjcType = BrBaseViewModel*;

    using Boxed = BrBaseViewModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

