// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#import <Foundation/Foundation.h>
@class BrNetworkManager;
@protocol BrNetworkListener;


@interface BrNetworkManager : NSObject

+ (nullable BrNetworkManager *)create;

- (nonnull NSArray<NSString *> *)getBibleBooks:(nullable id<BrNetworkListener>)listener;

@end
