// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

#import "BRNetworkListener+Private.h"
#import "BRNetworkListener.h"
#import "BRBaseViewModel+Private.h"
#import "DJIObjcWrapperCache+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class NetworkListener::ObjcProxy final
: public ::biblereader::NetworkListener
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void complete(const std::shared_ptr<::biblereader::BaseViewModel> & c_view_model) override
    {
        @autoreleasepool {
            [Handle::get() complete:(::djinni_generated::BaseViewModel::fromCpp(c_view_model))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto NetworkListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto NetworkListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
