// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

#import "BRNetworkManager+Private.h"
#import "BRNetworkManager.h"
#import "BRNetworkListener+Private.h"
#import "BRNetworkManager+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface BRNetworkManager ()

- (id)initWithCpp:(const std::shared_ptr<::biblereader::NetworkManager>&)cppRef;

@end

@implementation BRNetworkManager {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::biblereader::NetworkManager>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::biblereader::NetworkManager>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable BRNetworkManager *)create {
    try {
        auto r = ::biblereader::NetworkManager::create();
        return ::djinni_generated::NetworkManager::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)getBibleBooks:(nullable id<BRNetworkListener>)listener {
    try {
        _cppRefHandle.get()->get_bible_books(::djinni_generated::NetworkListener::toCpp(listener));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto NetworkManager::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto NetworkManager::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<BRNetworkManager>(cpp);
}

}  // namespace djinni_generated

@end
