// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#include "br_network_manager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class BrNetworkManager;

namespace djinni_generated {

class BrNetworkManager
{
public:
    using CppType = std::shared_ptr<::biblereader::BrNetworkManager>;
    using CppOptType = std::shared_ptr<::biblereader::BrNetworkManager>;
    using ObjcType = BrNetworkManager*;

    using Boxed = BrNetworkManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

