// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

#include "network_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol BRNetworkListener;

namespace djinni_generated {

class NetworkListener
{
public:
    using CppType = std::shared_ptr<::biblereader::NetworkListener>;
    using CppOptType = std::shared_ptr<::biblereader::NetworkListener>;
    using ObjcType = id<BRNetworkListener>;

    using Boxed = NetworkListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

