// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

#import <Foundation/Foundation.h>
@class BRBaseViewModel;


@protocol BRNetworkListener

- (void)complete:(nullable BRBaseViewModel *)viewModel;

@end
