// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#import "BrNetworkListener+Private.h"
#import "BrNetworkListener.h"
#import "BrBaseViewModel+Private.h"
#import "DJIObjcWrapperCache+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class BrNetworkListener::ObjcProxy final
: public ::biblereader::BrNetworkListener
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void complete(const std::shared_ptr<::biblereader::BrBaseViewModel> & c_view_model) override
    {
        @autoreleasepool {
            [Handle::get() complete:(::djinni_generated::BrBaseViewModel::fromCpp(c_view_model))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto BrNetworkListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto BrNetworkListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
