// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

#import <Foundation/Foundation.h>
@class BRNetworkManager;
@protocol BRNetworkListener;


@interface BRNetworkManager : NSObject

+ (nullable BRNetworkManager *)create;

- (void)getBibleBooks:(nullable id<BRNetworkListener>)listener;

@end
