// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#import <Foundation/Foundation.h>
@class BrBaseViewModel;


@protocol BrNetworkListener

- (void)complete:(nullable BrBaseViewModel *)viewModel;

@end
