// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

#include "network_manager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class BRNetworkManager;

namespace djinni_generated {

class NetworkManager
{
public:
    using CppType = std::shared_ptr<::biblereader::NetworkManager>;
    using CppOptType = std::shared_ptr<::biblereader::NetworkManager>;
    using ObjcType = BRNetworkManager*;

    using Boxed = NetworkManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

