// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#pragma once

#include <memory>
#include <string>

namespace biblereader {

class BaseViewModel {
public:
    virtual ~BaseViewModel() {}

    static std::shared_ptr<BaseViewModel> create();

    virtual void set_xml(const std::string & xml) = 0;

    virtual std::string get_xml() = 0;
};

}  // namespace biblereader
