// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from base_view_model.djinni

#pragma once

#include <string>
#include <utility>

namespace biblereader {

struct BaseRecord; // Requiring extended class

struct BaseRecordBase {
    std::string xml;

    BaseRecordBase(std::string xml_)
    : xml(std::move(xml_))
    {}

    virtual ~BaseRecordBase() = default;

protected:
    BaseRecordBase(const BaseRecordBase&) = default;
    BaseRecordBase(BaseRecordBase&&) = default;
    BaseRecordBase& operator=(const BaseRecordBase&) = default;
    BaseRecordBase& operator=(BaseRecordBase&&) = default;
};

}  // namespace biblereader
