// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#pragma once

#include <memory>

namespace biblereader {

class BrBaseViewModel {
public:
    virtual ~BrBaseViewModel() {}

    static std::shared_ptr<BrBaseViewModel> create();
};

}  // namespace biblereader
