// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#pragma once

#include <memory>
#include <string>

namespace biblereader {

class BrBaseViewModel {
public:
    virtual ~BrBaseViewModel() {}

    static std::shared_ptr<BrBaseViewModel> create();

    virtual void set_xml(const std::string & xml) = 0;
};

}  // namespace biblereader
