// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_base_view_model.djinni

#pragma once

#include <string>
#include <utility>

namespace biblereader {

struct BrBaseRecord; // Requiring extended class

struct BrBaseRecordBase {
    std::string xml;

    BrBaseRecordBase(std::string xml_)
    : xml(std::move(xml_))
    {}

    virtual ~BrBaseRecordBase() = default;

protected:
    BrBaseRecordBase(const BrBaseRecordBase&) = default;
    BrBaseRecordBase(BrBaseRecordBase&&) = default;
    BrBaseRecordBase& operator=(const BrBaseRecordBase&) = default;
    BrBaseRecordBase& operator=(BrBaseRecordBase&&) = default;
};

}  // namespace biblereader
