// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#pragma once

#include <memory>

namespace biblereader {

class BrBaseViewModel;

class BrNetworkListener {
public:
    virtual ~BrNetworkListener() {}

    virtual void complete(const std::shared_ptr<BrBaseViewModel> & view_model) = 0;
};

}  // namespace biblereader
