// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#pragma once

#include <memory>

namespace biblereader {

class BrNetworkListener;

class BrNetworkManager {
public:
    virtual ~BrNetworkManager() {}

    static std::shared_ptr<BrNetworkManager> create();

    virtual void get_bible_books(const std::shared_ptr<BrNetworkListener> & listener) = 0;
};

}  // namespace biblereader
