// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from br_network_manager.djinni

#pragma once

namespace biblereader {

class BrNetworkListener {
public:
    virtual ~BrNetworkListener() {}

    virtual void complete() = 0;
};

}  // namespace biblereader
