// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

#pragma once

#include <memory>

namespace biblereader {

class BaseViewModel;

class NetworkListener {
public:
    virtual ~NetworkListener() {}

    virtual void complete(const std::shared_ptr<BaseViewModel> & view_model) = 0;
};

}  // namespace biblereader
