// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_manager.djinni

#pragma once

#include <memory>

namespace biblereader {

class NetworkListener;

class NetworkManager {
public:
    virtual ~NetworkManager() {}

    static std::shared_ptr<NetworkManager> create();

    virtual void get_bible_books(const std::shared_ptr<NetworkListener> & listener) = 0;
};

}  // namespace biblereader
